project:
  title: "Stan Reference Manual"
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 2

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    subtitle: "Version {{< env STAN_DOCS_VERSION >}}"
    include-in-header: "../header.tex"
    toc-title: "Table of Contents"
    highlight-style: tango
    keep-tex: false
    colorlinks: true
    linkcolor: darkblue
    urlcolor: darkred
    citecolor: darkgreen

book:
  title: "Stan Reference Manual"
  author: "Stan Development Team"
  search: true
  sidebar:
    foreground: "#052744"
    background: "#FEFBF2"
    title: false

  chapters:
    - index.qmd
    - part: "Language"
      chapters:
        - encoding.Rmd
        - includes.Rmd
        - comments.Rmd
        - whitespace.Rmd
        - types.Rmd
        - expressions.Rmd
        - statements.Rmd
        - blocks.Rmd
        - user-functions.Rmd
        - transforms.Rmd
        - syntax.Rmd
        - execution.Rmd
        - deprecations.Rmd
        - removals.Rmd

    - part: "Algorithms"
      chapters:
        - mcmc.Rmd
        - analysis.Rmd
        - optimization.Rmd
        - pathfinder.Rmd
        - variational.Rmd
        - laplace.Rmd
        - diagnostics.Rmd

    - part: "Usage"
      chapters:
        - reproducibility.Rmd
        - licenses.Rmd

    - references.Rmd
