project:
  title: "Stan User's Guide"
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 3

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    include-in-header: "../header.tex"
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    highlight-style: tango
    keep-tex: true

book:
  title: "Stan User's Guide"
  author: "Stan Development Team"
  search: true
  sidebar:
    foreground: "#052744"
    background: "#FEFBF2"
    title: false

  chapters:
    - index.qmd
    - part: "Example Models"
      chapters:
        - regression.Rmd
        - time-series.Rmd
        - missing-data.Rmd
        - truncation-censoring.Rmd
        - finite-mixtures.Rmd
        - measurement-error.Rmd
        - latent-discrete.Rmd
        - sparse-ragged.Rmd
        - clustering.Rmd
        - gaussian-processes.Rmd
        - hyperspherical-models.Rmd
        - algebraic-equations.Rmd
        - odes.Rmd
        - one-dimensional-integrals.Rmd
        - complex-numbers.Rmd
        - dae.Rmd
    - part:  "Programming Techniques"
      chapters:
        - floating-point.Rmd
        - matrices-arrays.Rmd
        - multi-indexing.Rmd
        - user-functions.Rmd
        - custom-probability.Rmd
        - proportionality-constants.Rmd
        - problematic-posteriors.Rmd
        - reparameterization.Rmd
        - efficiency-tuning.Rmd
        - parallelization.Rmd
    - part: "Posterior Inference & Model Checking"
      chapters:
        - posterior-prediction.Rmd
        - simulation-based-calibration.Rmd
        - posterior-predictive-checks.Rmd
        - cross-validation.Rmd
        - poststratification.Rmd
        - decision-analysis.Rmd
        - bootstrap.Rmd
    - part: "Appendices"
      chapters:
        - using-stanc.Rmd
        - style-guide.Rmd
        - for-bugs-users.Rmd
    - references.Rmd
