project:
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike

format:
  pdf:
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    include-in-header: "header.tex"
    keep-tex: true
    keep-latex: true
    keep-md: true

book:
  title: "Stan User's Guide"
  author: "Stan Development Team"
  chapters:
    - index.qmd
    - part: part1.Rmd
      chapters:
        - regression.Rmd
        - time-series.Rmd
        - truncation-censoring.Rmd
        - finite-mixtures.Rmd
        - measurement-error.Rmd
        - latent-discrete.Rmd
        - sparse-ragged.Rmd
        - clustering.Rmd
        - gaussian-processes.Rmd
        - hyperspherical-models.Rmd
        - algebraic-equations.Rmd
        - odes.Rmd
        - one-dimensional-integrals.Rmd
        - complex-numbers.Rmd
        - dae.Rmd
    - references.Rmd
