project:
  type: book


bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 2

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    include-after-body: js.html
    code-copy: true
    code-fold: true
    code-overflow: wrap
    df-print: kable
    html-math-method: mathjax
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    keep-md: true
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    include-in-header: "header.tex"
    keep-tex: true
    keep-latex: true
    keep-md: true
    toc-title: "Table of Contents"

book:
  title: "Stan User's Guide"
  author: "Stan Development Team"
  search: true
  sidebar:
    logo: ../img/logo_tm.png
    logo-alt: "Stan logo"
    foreground: "#052744"
    background: "#FEFBF2"
    title: false

  chapters:
    - index.qmd
    - part: part1.Rmd
      chapters:
        - regression.Rmd
        - time-series.Rmd
        - truncation-censoring.Rmd
        - finite-mixtures.Rmd
        - measurement-error.Rmd
        - latent-discrete.Rmd
        - sparse-ragged.Rmd
        - clustering.Rmd
        - gaussian-processes.Rmd
        - hyperspherical-models.Rmd
        - algebraic-equations.Rmd
        - odes.Rmd
        - one-dimensional-integrals.Rmd
        - complex-numbers.Rmd
        - dae.Rmd
    - part: part2.Rmd
      chapters:
        - floating-point.Rmd
        - matrices-arrays.Rmd
        - multi-indexing.Rmd
        - user-functions.Rmd
        - custom-probability.Rmd
        - proportionality-constants.Rmd
        - problematic-posteriors.Rmd
        - reparameterization.Rmd
        - efficiency-tuning.Rmd
        - parallelization.Rmd
    - part: part3.Rmd
      chapters:
        - posterior-prediction.Rmd
        - simulation-based-calibration.Rmd
        - posterior-predictive-checks.Rmd
        - cross-validation.Rmd
        - poststratification.Rmd
        - decision-analysis.Rmd
        - bootstrap.Rmd
    - part: part-appendices.Rmd
      chapters:
        - using-stanc.Rmd
        - style-guide.Rmd
        - for-bugs-users.Rmd
    - references.Rmd
