project:
  title: "Stan Functions Reference"
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 2

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    documentclass: book
    subtitle: "Version {{< env STAN_DOCS_VERSION >}}"
    include-in-header: "../header.tex"
    include-after-body: "../postamble.tex"
    toc-title: "Table of Contents"
    syntax-definitions:
      - ../stan.xml
    keep-tex: false
    highlight-style: tango
    colorlinks: true
    linkcolor: darkblue
    urlcolor: darkblue
    citecolor: darkgreen

book:
  title: "Stan Functions Reference"
  author: "Stan Development Team"
  search: true

  chapters:
    - index.qmd
    - part: "Built-in Functions"
      chapters: 
        - void_functions.Rmd
        - integer-valued_basic_functions.Rmd
        - real-valued_basic_functions.Rmd
        - complex-valued_basic_functions.Rmd
        - array_operations.Rmd
        - matrix_operations.Rmd
        - complex_matrix_operations.Rmd
        - sparse_matrix_operations.Rmd
        - mixed_operations.Rmd
        - compound_arithmetic_and_assignment.Rmd
        - higher-order_functions.Rmd
        - deprecated_functions.Rmd
        - removed_functions.Rmd
        - conventions_for_probability_functions.Rmd
    - part: "Discrete Distributions"
      chapters: 
        - binary_distributions.Rmd
        - bounded_discrete_distributions.Rmd
        - unbounded_discrete_distributions.Rmd
        - multivariate_discrete_distributions.Rmd
    - part: "Continuous Distributions"
      chapters: 
        - unbounded_continuous_distributions.Rmd
        - positive_continuous_distributions.Rmd
        - positive_lower-bounded_distributions.Rmd
        - continuous_distributions_on_0_1.Rmd
        - circular_distributions.Rmd
        - bounded_continuous_distributions.Rmd
        - distributions_over_unbounded_vectors.Rmd
        - simplex_distributions.Rmd
        - correlation_matrix_distributions.Rmd
        - covariance_matrix_distributions.Rmd
    - part: "Additional Distributions"
      chapters: 
        - hidden_markov_models.Rmd
    - part: "Appendix"
      chapters: 
        - mathematical_functions.Rmd
    - references.Rmd
