project:
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 3

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    documentclass: book
    include-in-header: "../header.tex"
    include-after-body: "postamble.tex"
    toc-title: "Table of Contents"
    keep-tex: true

book:
  title: "Stan Functions Reference"
  author: "Stan Development Team"
  search: true
  sidebar:
    foreground: "#052744"
    background: "#FEFBF2"
    title: false

  chapters:
    - index.qmd
    - part: built-in_functions.Rmd
      chapters: 
        - void_functions.Rmd
        - integer-valued_basic_functions.Rmd
        - real-valued_basic_functions.Rmd
        - complex-valued_basic_functions.Rmd
        - array_operations.Rmd
        - matrix_operations.Rmd
        - complex_matrix_operations.Rmd
        - sparse_matrix_operations.Rmd
        - mixed_operations.Rmd
        - compound_arithmetic_and_assignment.Rmd
        - higher-order_functions.Rmd
        - deprecated_functions.Rmd
        - removed_functions.Rmd
        - conventions_for_probability_functions.Rmd
    - part: discrete_distributions.Rmd
      chapters: 
        - binary_distributions.Rmd
        - bounded_discrete_distributions.Rmd
        - unbounded_discrete_distributions.Rmd
        - multivariate_discrete_distributions.Rmd
    - part: continuous_distributions.Rmd
      chapters: 
        - unbounded_continuous_distributions.Rmd
        - positive_continuous_distributions.Rmd
        - positive_lower-bounded_distributions.Rmd
        - continuous_distributions_on_0_1.Rmd
        - circular_distributions.Rmd
        - bounded_continuous_distributions.Rmd
        - distributions_over_unbounded_vectors.Rmd
        - simplex_distributions.Rmd
        - correlation_matrix_distributions.Rmd
        - covariance_matrix_distributions.Rmd
    - part: additional_distributions.Rmd
      chapters: 
        - hidden_markov_models.Rmd
    - appendix.Rmd
    - mathematical_functions.Rmd
    - references.Rmd
