project:
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 2

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: "quarto_styles.css"
    include-after-body: "js.html"
    code-copy: true
    code-fold: true
    code-overflow: wrap
    df-print: kable
    html-math-method: mathjax
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 200px
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    include-in-header: "header.tex"
    toc-title: "Table of Contents"

book:
  title: "Stan Reference Manual"
  author: "Stan Development Team"
  search: true
  sidebar:
    foreground: "#052744"
    background: "#FEFBF2"
    title: false

  chapters:
    - index.qmd
    - part: quickstart_guide.Rmd
      chapters:
        - installation.Rmd
        - example_model_data.Rmd
        - compiling_stan_programs.Rmd
        - mcmc_sampling_intro.Rmd
        - optimization_intro.Rmd
        - pathfinder_intro.Rmd
        - variational_intro.Rmd
        - generate_quantities_intro.Rmd

    - part: ref_section.Rmd
      chapters:
        - command_line_options.Rmd
        - mcmc_config.Rmd
        - optimize_config.Rmd
        - pathfinder_config.Rmd
        - variational_config.Rmd
        - generate_quantities_config.Rmd
        - laplace_sample_config.Rmd
        - log_prob_config.Rmd
        - diagnose_config.Rmd
        - parallelization.Rmd

    - part: tools_section.Rmd
      chapters:
        - stanc.Rmd
        - stansummary.Rmd
        - diagnose_utility.Rmd
        - print.Rmd

    - part: apdx_section.Rmd
      chapters:
        - stan_csv_apdx.Rmd
        - json_apdx.Rmd
        - rdump_apdx.Rmd
        - external_code.Rmd
