project:
  title: "CmdStan User's Guide"
  type: book

bibliography: [../bibtex/all.bib]
biblio-style: apalike
syntax-definition: "../stan.xml"
toc: true
toc-depth: 2

format:
  pdf:
    latex-tinytex: false
    block-headings: false
    pdf-engine: "pdflatex"
    latex-engine: "pdflatex"
    latex-auto-install: true
    documentclass: book
    subtitle: "Version {{< env STAN_DOCS_VERSION >}}"
    include-in-header: "../header.tex"
    toc-title: "Table of Contents"
    highlight-style: tango
    keep-tex: false
    colorlinks: true
    linkcolor: darkblue
    urlcolor: darkblue
    citecolor: darkgreen

book:
  title: "CmdStan User's Guide"
  author: "Stan Development Team"
  search: true

  chapters:
    - index.qmd
    - part: "Quickstart Guide"
      chapters:
        - installation.Rmd
        - example_model_data.Rmd
        - compiling_stan_programs.Rmd
        - mcmc_sampling_intro.Rmd
        - optimization_intro.Rmd
        - pathfinder_intro.Rmd
        - variational_intro.Rmd
        - generate_quantities_intro.Rmd

    - part: "Reference Manual"
      chapters:
        - command_line_options.Rmd
        - mcmc_config.Rmd
        - optimize_config.Rmd
        - pathfinder_config.Rmd
        - variational_config.Rmd
        - generate_quantities_config.Rmd
        - laplace_sample_config.Rmd
        - log_prob_config.Rmd
        - diagnose_config.Rmd
        - parallelization.Rmd

    - part: "CmdStan Utilities"
      chapters:
        - stanc.Rmd
        - stansummary.Rmd
        - diagnose_utility.Rmd
        - print.Rmd

    - part: "Appendices"
      chapters:
        - stan_csv_apdx.Rmd
        - json_apdx.Rmd
        - rdump_apdx.Rmd
        - external_code.Rmd

    - bib.Rmd
