project:
  title: "Stan Docs"
  type: website
  output-dir: _website
  render:
    - "index.qmd"
    - "404.qmd"
    - "cmdstan-guide/overview.qmd"
    - "functions-reference/overview.qmd"
    - "reference-manual/overview.qmd"
    - "stan-users-guide/overview.qmd"
    - "cmdstan-guide/*.Rmd"
    - "functions-reference/*.Rmd"
    - "reference-manual/*.Rmd"
    - "stan-users-guide/*.Rmd"
    - "!sdlc.Rmd"

bibliography: bibtex/all.bib
biblio-style: apalike

title-prefix: ""
toc: true
toc-depth: 3

website:
  favicon: img/logo_tm.png
  image: img/logo_tm.png
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/stan-dev/docs
  repo-subdir: src
  repo-branch: master
  repo-actions: [edit, issue]

  navbar:
    logo: "img/logo_tm.png"
    logo-alt: "Stan logo"
    foreground: "#F2E5BD"
    background: "#052744"
    title: false
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Stan Users Guide"
        href: stan-users-guide/overview.qmd
      - text: "Reference Manual"
        href: reference-manual/overview.qmd
      - text: "Functions Reference"
        href: functions-reference/overview.qmd
      - text: "Interfaces"
        menu:
          - text: "CmdStan"
            href: cmdstan-guide/overview.qmd
          - text: "CmdStanPy"
            url: https://mc-stan.org/cmdstanpy
          - text: "CmdStanR"
            url: https://mc-stan.org/cmdstanr
          - text: "PyStan"
            url: https://mc-stan.org/pystan
          - text: "RStan"
            url: https://mc-stan.org/rstan
          - text: "Stan.jl"
            url: http://stanjulia.github.io/Stan.jl/stable/INTRO/
      - text: "Other Packages"
        menu:
          - text: "Bayesplot"
            href: https://mc-stan.org/bayesplot/
          - text: "BridgeStan"
            href: https://roualdes.github.io/bridgestan/latest/
          - text: "BRMS"
            url: https://paul-buerkner.github.io/brms/
          - text: "loo"
            href: https://mc-stan.org/loo/
          - text: "RStanArm"
            url: https://mc-stan.org/rstanarm

    tools:
      - icon: github
        url: https://github.com/stan-dev
      - icon: chat-text-fill
        href: "https://discourse.mc-stan.org"

  sidebar:
    - id: stan-users-guide
      title: "Stan User's Guide"
      search: true
      foreground: "#052744"
      background: "#FEFCF9"
      contents:
        - stan-users-guide/overview.qmd
        - section: "Version {{< env STAN_DOCS_VERSION >}}"
        - section: "Example Models"
          contents:
            - stan-users-guide/regression.Rmd
            - stan-users-guide/time-series.Rmd
            - stan-users-guide/missing-data.Rmd
            - stan-users-guide/truncation-censoring.Rmd
            - stan-users-guide/finite-mixtures.Rmd
            - stan-users-guide/measurement-error.Rmd
            - stan-users-guide/latent-discrete.Rmd
            - stan-users-guide/sparse-ragged.Rmd
            - stan-users-guide/clustering.Rmd
            - stan-users-guide/gaussian-processes.Rmd
            - stan-users-guide/hyperspherical-models.Rmd
            - stan-users-guide/algebraic-equations.Rmd
            - stan-users-guide/odes.Rmd
            - stan-users-guide/one-dimensional-integrals.Rmd
            - stan-users-guide/complex-numbers.Rmd
            - stan-users-guide/dae.Rmd
        - section:  "Programming Techniques"
          contents:
            - stan-users-guide/floating-point.Rmd
            - stan-users-guide/matrices-arrays.Rmd
            - stan-users-guide/multi-indexing.Rmd
            - stan-users-guide/user-functions.Rmd
            - stan-users-guide/custom-probability.Rmd
            - stan-users-guide/proportionality-constants.Rmd
            - stan-users-guide/problematic-posteriors.Rmd
            - stan-users-guide/reparameterization.Rmd
            - stan-users-guide/efficiency-tuning.Rmd
            - stan-users-guide/parallelization.Rmd
        - section: "Posterior Inference & Model Checking"
          contents:
            - stan-users-guide/posterior-prediction.Rmd
            - stan-users-guide/simulation-based-calibration.Rmd
            - stan-users-guide/posterior-predictive-checks.Rmd
            - stan-users-guide/cross-validation.Rmd
            - stan-users-guide/poststratification.Rmd
            - stan-users-guide/decision-analysis.Rmd
            - stan-users-guide/bootstrap.Rmd
        - section: "Appendices"
          contents:
            - stan-users-guide/using-stanc.Rmd
            - stan-users-guide/style-guide.Rmd
            - stan-users-guide/for-bugs-users.Rmd

    - id: reference-manual
      title: "Reference Manual"
      contents:
        - reference-manual/overview.qmd
        - section: "Version {{< env STAN_DOCS_VERSION >}}"
        - section: "Language"
          contents:
            - reference-manual/encoding.Rmd
            - reference-manual/includes.Rmd
            - reference-manual/comments.Rmd
            - reference-manual/whitespace.Rmd
            - reference-manual/types.Rmd
            - reference-manual/expressions.Rmd
            - reference-manual/statements.Rmd
            - reference-manual/blocks.Rmd
            - reference-manual/user-functions.Rmd
            - reference-manual/transforms.Rmd
            - reference-manual/syntax.Rmd
            - reference-manual/execution.Rmd
            - reference-manual/deprecations.Rmd
            - reference-manual/removals.Rmd
        - section: "Algorithms"
          contents:
            - reference-manual/mcmc.Rmd
            - reference-manual/analysis.Rmd
            - reference-manual/optimization.Rmd
            - reference-manual/pathfinder.Rmd
            - reference-manual/variational.Rmd
            - reference-manual/laplace.Rmd
            - reference-manual/diagnostics.Rmd
        - section: "Usage"
          contents:
            - reference-manual/reproducibility.Rmd
            - reference-manual/licenses.Rmd

    - id: functions-reference
      title: "Stan Functions"
      contents:
        - functions-reference/overview.qmd
        - section: "Version {{< env STAN_DOCS_VERSION >}}"
        - section: "Built-in Functions"
          contents:
            - functions-reference/void_functions.Rmd
            - functions-reference/integer-valued_basic_functions.Rmd
            - functions-reference/real-valued_basic_functions.Rmd
            - functions-reference/complex-valued_basic_functions.Rmd
            - functions-reference/array_operations.Rmd
            - functions-reference/matrix_operations.Rmd
            - functions-reference/complex_matrix_operations.Rmd
            - functions-reference/sparse_matrix_operations.Rmd
            - functions-reference/mixed_operations.Rmd
            - functions-reference/compound_arithmetic_and_assignment.Rmd
            - functions-reference/higher-order_functions.Rmd
            - functions-reference/deprecated_functions.Rmd
            - functions-reference/removed_functions.Rmd
            - functions-reference/conventions_for_probability_functions.Rmd
        - section: "Discrete Distributions"
          contents:
            - functions-reference/binary_distributions.Rmd
            - functions-reference/bounded_discrete_distributions.Rmd
            - functions-reference/unbounded_discrete_distributions.Rmd
            - functions-reference/multivariate_discrete_distributions.Rmd
        - section: "Continuous Distributions"
          contents:
            - functions-reference/unbounded_continuous_distributions.Rmd
            - functions-reference/positive_continuous_distributions.Rmd
            - functions-reference/positive_lower-bounded_distributions.Rmd
            - functions-reference/continuous_distributions_on_0_1.Rmd
            - functions-reference/circular_distributions.Rmd
            - functions-reference/bounded_continuous_distributions.Rmd
            - functions-reference/distributions_over_unbounded_vectors.Rmd
            - functions-reference/simplex_distributions.Rmd
            - functions-reference/correlation_matrix_distributions.Rmd
            - functions-reference/covariance_matrix_distributions.Rmd
        - section: "Additional Distributions"
          contents:
            - functions-reference/hidden_markov_models.Rmd
        - section: "Appendix"
          contents:
            - functions-reference/mathematical_functions.Rmd

    - id: cmdstan-guide
      title: "CmdStan Guide"
      contents:
        - cmdstan-guide/overview.qmd
        - section: "Version {{< env STAN_DOCS_VERSION >}}"
        - section: "Quickstart Guide"
          contents:
            - cmdstan-guide/installation.Rmd
            - cmdstan-guide/example_model_data.Rmd
            - cmdstan-guide/compiling_stan_programs.Rmd
            - cmdstan-guide/mcmc_sampling_intro.Rmd
            - cmdstan-guide/optimization_intro.Rmd
            - cmdstan-guide/pathfinder_intro.Rmd
            - cmdstan-guide/variational_intro.Rmd
            - cmdstan-guide/generate_quantities_intro.Rmd
        - section: "Reference Manual"
          contents:
            - cmdstan-guide/command_line_options.Rmd
            - cmdstan-guide/mcmc_config.Rmd
            - cmdstan-guide/optimize_config.Rmd
            - cmdstan-guide/pathfinder_config.Rmd
            - cmdstan-guide/variational_config.Rmd
            - cmdstan-guide/generate_quantities_config.Rmd
            - cmdstan-guide/laplace_sample_config.Rmd
            - cmdstan-guide/log_prob_config.Rmd
            - cmdstan-guide/diagnose_config.Rmd
            - cmdstan-guide/parallelization.Rmd
        - section: "Tools and Utilities"
          contents:
            - cmdstan-guide/stanc.Rmd
            - cmdstan-guide/stansummary.Rmd
            - cmdstan-guide/diagnose_utility.Rmd
            - cmdstan-guide/print.Rmd
        - section: "Appendices"
          contents:
            - cmdstan-guide/stan_csv_apdx.Rmd
            - cmdstan-guide/json_apdx.Rmd
            - cmdstan-guide/rdump_apdx.Rmd
            - cmdstan-guide/external_code.Rmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    syntax-definitions:
      - stan.xml
    highlight-style: tango
    code-copy: true
    code-overflow: wrap
    css: quarto_styles.css
    include-after-body: js.html
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
